//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace NMatrix.Generated
{
    using System;
    using System.Xml;
    using NMatrix.XGoF.SampleProject;
    
    
    public class dsPublishers : DataObject
    {
        
        
			
			protected object GetInstance()
			{
				return new dsPublishers();
			}
			
			public void Save()
			{
				DAL.SaveObject(this);
			}

			public void Load()
			{
				DAL.LoadObject(this);
			}
		
        public dsPublishers()
        {
            System.Diagnostics.Debug.WriteLine("Constructing object of type dsPublishers");
        }
        
        public class publishers : DataObject
        {
            
            
			
				System.String _pub_id;
			
				System.String _pub_name;
			
				System.String _city;
			
				System.String _state;
			
				System.String _country;
			
			protected object GetInstance()
			{
				return new publishers();
			}
			
			public void Save()
			{
				DAL.SaveObject(this);
			}

			public void Load()
			{
				DAL.LoadObject(this);
			}
		
            public publishers()
            {
                System.Diagnostics.Debug.WriteLine("Constructing object of type publishers");
            }
            
            public virtual string pub_id
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property pub_id");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: pub_id");
					return _pub_id;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property pub_id");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: pub_id");
					_pub_id = value;
			
                }
            }
            
            public virtual string pub_name
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property pub_name");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: pub_name");
					return _pub_name;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property pub_name");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: pub_name");
					_pub_name = value;
			
                }
            }
            
            public virtual string city
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property city");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: city");
					return _city;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property city");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: city");
					_city = value;
			
                }
            }
            
            public virtual string state
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property state");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: state");
					return _state;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property state");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: state");
					_state = value;
			
                }
            }
            
            public virtual string country
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property country");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: country");
					return _country;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property country");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: country");
					_country = value;
			
                }
            }
        }
        
        public class titles : DataObject
        {
            
            
			
				System.String _title_id;
			
				System.String _title;
			
				System.String _type;
			
				System.String _titlepub_id;
			
				System.Decimal _price;
			
				System.Decimal _advance;
			
				System.Int32 _royalty;
			
				System.Int32 _ytd_sales;
			
				System.String _notes;
			
				System.DateTime _pubdate;
			
			protected object GetInstance()
			{
				return new titles();
			}
			
			public void Save()
			{
				DAL.SaveObject(this);
			}

			public void Load()
			{
				DAL.LoadObject(this);
			}
		
            public titles()
            {
                System.Diagnostics.Debug.WriteLine("Constructing object of type titles");
            }
            
            public virtual string title_id
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property title_id");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: title_id");
					return _title_id;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property title_id");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: title_id");
					_title_id = value;
			
                }
            }
            
            public virtual string title
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property title");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: title");
					return _title;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property title");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: title");
					_title = value;
			
                }
            }
            
            public virtual string type
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property type");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: type");
					return _type;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property type");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: type");
					_type = value;
			
                }
            }
            
            public virtual string titlepub_id
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property titlepub_id");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: titlepub_id");
					return _titlepub_id;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property titlepub_id");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: titlepub_id");
					_titlepub_id = value;
			
                }
            }
            
            public virtual System.Decimal price
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property price");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: price");
					return _price;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property price");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: price");
					_price = value;
			
                }
            }
            
            public virtual System.Decimal advance
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property advance");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: advance");
					return _advance;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property advance");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: advance");
					_advance = value;
			
                }
            }
            
            public virtual int royalty
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property royalty");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: royalty");
					return _royalty;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property royalty");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: royalty");
					_royalty = value;
			
                }
            }
            
            public virtual int ytd_sales
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property ytd_sales");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: ytd_sales");
					return _ytd_sales;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property ytd_sales");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: ytd_sales");
					_ytd_sales = value;
			
                }
            }
            
            public virtual string notes
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property notes");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: notes");
					return _notes;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property notes");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: notes");
					_notes = value;
			
                }
            }
            
            public virtual System.DateTime pubdate
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property pubdate");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: pubdate");
					return _pubdate;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property pubdate");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: pubdate");
					_pubdate = value;
			
                }
            }
        }
        
        public class titleauthors : DataObject
        {
            
            
			
				System.String _au_id;
			
				System.String _title_id;
			
				System.Byte _au_ord;
			
				System.Int32 _royaltyper;
			
			protected object GetInstance()
			{
				return new titleauthors();
			}
			
			public void Save()
			{
				DAL.SaveObject(this);
			}

			public void Load()
			{
				DAL.LoadObject(this);
			}
		
            public titleauthors()
            {
                System.Diagnostics.Debug.WriteLine("Constructing object of type titleauthors");
            }
            
            public virtual string au_id
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property au_id");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: au_id");
					return _au_id;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property au_id");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: au_id");
					_au_id = value;
			
                }
            }
            
            public virtual string title_id
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property title_id");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: title_id");
					return _title_id;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property title_id");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: title_id");
					_title_id = value;
			
                }
            }
            
            public virtual System.Byte au_ord
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property au_ord");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: au_ord");
					return _au_ord;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property au_ord");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: au_ord");
					_au_ord = value;
			
                }
            }
            
            public virtual int royaltyper
            {
                get
                {
                    System.Diagnostics.Debug.WriteLine("Getting property royaltyper");
                    
					//System.Diagnostics.Debug.WriteLine("Getting property: royaltyper");
					return _royaltyper;
			
                }
                set
                {
                    System.Diagnostics.Debug.WriteLine("Setting property royaltyper");
                    
					//System.Diagnostics.Debug.WriteLine("Setting property: royaltyper");
					_royaltyper = value;
			
                }
            }
        }
    }
}
